# -*- coding: utf-8 -*-
"""todo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12FlUI1cstqKWg_LqCCTdXcNYD_2AXh2v
"""

import os

TODO_FILE = "todo.txt"

def load_tasks():
  tasks = []
  if os.path.exists(TODO_FILE):
    with open(TODO_FILE, "r") as f:
      for line in f:
        tasks.append(line.strip())
  return tasks

def save_tasks(tasks):
  with open(TODO_FILE, "w") as f:
    for task in tasks:
      f.write(task + "\n")

def add_task(tasks, task):
  tasks.append(task)
  save_tasks(tasks)
  print(f"Task '{task}' added.")

def remove_task(tasks, task_index):
  if 0 <= task_index < len(tasks):
    removed_task = tasks.pop(task_index)
    print(f"Task '{removed_task}' removed.")
  else:
    print("Invalid task index.")

def view_tasks(tasks):
  if not tasks:
    print("Your to-do list is empty.")
  else:
    print("Your To-Do List:")
    for i, task in enumerate(tasks, start = 1):
      print(f"{i}. {task}")

def todo():
  tasks = load_tasks()

  while True:
    print("\nChoose an action:")
    print("1. Add Task")
    print("2. Remove Task")
    print("3. View Tasks")
    print("4. Exit")

    choice = input("Enter your choice (1/2/3/4): ")

    if choice == "1":
      task = input("Enter the task to add: ")
      add_task(tasks, task)
    elif choice == "2":
      view_tasks(tasks)
      try:
        task_index = int(input("Enter the index of the task to remove: ")) - 1
        remove_task(tasks, task_index)
      except ValueError:
        print("Invalid input! Please enter a valid index.")
    elif choice == "3":
      view_tasks(tasks)
    elif choice == "4":
      print("Exiting To-Do List Application. Tasks saved.")
      break
    else:
      print("Invalid choice! Please try again.")

todo()